#!/bin/sh

PATH=${PATH}:/usr/bin

if [ "configure" = "$1" ]; then
  /usr/share/elasticsearch/bin/elasticsearch-plugin install -b file:///usr/share/[[artifactId]]/[[artifactId]]-[[project.version]].zip
fi

